import { injected } from '@/components/wallet/connectors'
import { useWeb3React } from '@web3-react/core'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const { active, account, library, connector, activate, deactivate } = useWeb3React()

  async function connect() {
    await activate(injected)
    console.log(account)
  }

  async function disconnect() {
    deactivate()
    console.log(account)
  }

  return (
    <>
      <Head>
        <title>Web3 Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center min-h-screen py-12 sm:px-6 lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <img
            className="w-auto h-12 mx-auto"
            src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
            alt="Workflow"
          />
          <h2 className="mt-6 text-3xl font-extrabold text-center text-gray-900">Web3 Wallet</h2>
        </div>

        <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div className="px-4 py-8 bg-white shadow sm:rounded-lg sm:px-10">
            <div>
              <label htmlFor="nep" className="block text-sm font-medium text-gray-700">
                NEP
              </label>
              <div className="relative mt-1 rounded-md shadow-sm">
                <input
                  type="number"
                  name="nep"
                  id="nep"
                  className="block w-full px-4 border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  placeholder="0.00"
                  aria-describedby="nep-cryptocurrency"
                />
              </div>
            </div>

            <div className="flex justify-center py-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="w-6 h-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
                />
              </svg>
            </div>

            <div>
              <label htmlFor="busd" className="block text-sm font-medium text-gray-700">
                BUSD
              </label>
              <div className="relative mt-1 rounded-md shadow-sm">
                <input
                  type="number"
                  name="busd"
                  id="busd"
                  className="block w-full px-4 border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  placeholder="0.00"
                  aria-describedby="busd-cryptocurrency"
                />
              </div>
            </div>
            <div className="mt-10">
              <button
                onClick={connect}
                type="submit"
                className="flex justify-center w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Check Wallet Details
              </button>
              {active ? (
                <span>
                  Connected with <b>{account}</b>
                </span>
              ) : (
                <span>Not Connected</span>
              )}
              <button
                onClick={disconnect}
                type="submit"
                className="flex justify-center w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Disconnect
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
